"""Update model snippet

Revision ID: 7492edd6acf4
Revises: fa07e5d3f7fa
Create Date: 2025-02-26 21:22:18.122418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7492edd6acf4'
down_revision: Union[str, None] = 'fa07e5d3f7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippet', sa.Column('share_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_snippet_share_id'), 'snippet', ['share_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snippet_share_id'), table_name='snippet')
    op.drop_column('snippet', 'share_id')
    # ### end Alembic commands ###
