"""Создание базы данных

Revision ID: fa07e5d3f7fa
Revises: 
Create Date: 2025-02-26 16:33:50.344950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa07e5d3f7fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('snippet', 'code',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('snippet', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('snippet', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('user', sa.Column('role', sa.Enum('ADMIN', 'USER', name='roleenum'), server_default=sa.text("'USER'"), nullable=False))
    op.drop_column('user', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'role')
    op.alter_column('snippet', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('snippet', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('snippet', 'code',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###
